import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#121315",
        "surface-dim": "#121315",
        "surface-bright": "#38393b",
        "surface-container-lowest": "#0d0e10",
        "surface-container-low": "#1b1c1e",
        "surface-container": "#1f2022",
        "surface-container-high": "#292a2c",
        "surface-container-highest": "#343537",
        "surface-variant": "#343537",
        "surface-tint": "#ffb874",
        "on-surface": "#e3e2e5",
        "on-surface-variant": "#dbc2ad",
        "inverse-surface": "#e3e2e5",
        "inverse-on-surface": "#303033",
        "inverse-primary": "#8c5000",
        outline: "#a38d7a",
        "outline-variant": "#554334",
        primary: "#ffbd7f",
        "on-primary": "#4b2800",
        "primary-container": "#ff9500",
        "on-primary-container": "#643700",
        "primary-fixed": "#ffdcbf",
        "primary-fixed-dim": "#ffb874",
        "on-primary-fixed": "#2d1600",
        "on-primary-fixed-variant": "#6a3b00",
        secondary: "#c6c6c9",
        "on-secondary": "#2f3133",
        "secondary-container": "#454749",
        "on-secondary-container": "#b4b5b7",
        "secondary-fixed": "#e2e2e5",
        "secondary-fixed-dim": "#c6c6c9",
        "on-secondary-fixed": "#1a1c1e",
        "on-secondary-fixed-variant": "#454749",
        tertiary: "#c9cad0",
        "on-tertiary": "#2e3035",
        "tertiary-container": "#adaeb4",
        "on-tertiary-container": "#404247",
        "tertiary-fixed": "#e2e2e8",
        "tertiary-fixed-dim": "#c5c6cc",
        "on-tertiary-fixed": "#191c20",
        "on-tertiary-fixed-variant": "#45474c",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#121315",
        "on-background": "#e3e2e5",
      },
      fontFamily: {
        "display-lg": ["var(--font-space-grotesk)", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-space-grotesk)", "system-ui", "sans-serif"],
        "label-md": ["var(--font-space-grotesk)", "system-ui", "sans-serif"],
        "body-md": ["var(--font-inter)", "system-ui", "sans-serif"],
        "body-lg": ["var(--font-inter)", "system-ui", "sans-serif"],
        sans: ["var(--font-space-grotesk)", "var(--font-inter)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-lg-mobile": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "24px",
        "section-gap": "160px",
        gutter: "32px",
        "container-max": "1280px",
        unit: "8px",
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "fade-in": "fadeIn 0.4s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
        shimmer: "shimmer 1.5s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translate(var(--parallax-x, 0px), var(--parallax-y, 0px)) translateY(0px)" },
          "50%": { transform: "translate(var(--parallax-x, 0px), var(--parallax-y, 0px)) translateY(-15px)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
